--- #YAML:1.0
name:                Getopt-Long
version:             2.38_02
abstract:            Module to handle parsing command line options
license:             ~
author:              
    - Johan Vromans (jvromans@squirrel.nl)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Pod::Usage:                    1.14
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
